# NumPy Exercises

#### Import NumPy as np

In [1]:
import numpy as np

#### Crear una matriz de 10 ceros

In [ ]:
# CODE HERE

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Crear una matriz con 10 unos

In [5]:
# CODE HERE
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### Create an array of 10 fives

In [ ]:
# CODE HERE


#### Create an array of the integers from 10 to 50

In [ ]:
# CODE HERE


#### Create an array of all the even integers from 10 to 50

In [ ]:
# CODE HERE


#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
# CODE HERE


In [ ]:
#podes partir del range del vector

In [ ]:
#hacer una de unos

In [ ]:
# multiplicarlas

#### Create a 3x3 identity matrix

In [ ]:
# CODE HERE


#### Use NumPy to generate a random number between 0 and 1

In [ ]:
# CODE HERE

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
# CODE HERE

#### Create the following matrix:

#### Create an array of 20 linearly spaced points between 0 and 1:

## Numpy Indexing and Selection

Ahora se le darán algunas matrices y se le pedirá que replique los resultados de la matriz resultante:

In [ ]:
# HERE IS THE GIVEN MATRIX CALLED MAT
# USE IT FOR THE FOLLOWING TASKS
mat = np.arange(1,26).reshape(5,5)
mat

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

### Now do the following

#### Get the sum of all the values in mat

In [ ]:
# CODE HERE

#### Get the standard deviation of the values in mat

In [ ]:
# CODE HERE

#### Get the sum of all the columns in mat

In [ ]:
# CODE HERE

array([55, 60, 65, 70, 75])

## Bonus Question

Trabajamos mucho con datos aleatorios con numpy, pero ¿hay alguna manera de asegurarnos de que siempre obtengamos los mismos números aleatorios? [Click Here for a Hint](https://www.google.com/search?q=numpy+random+seed&rlz=1C1CHBF_enUS747US747&oq=numpy+random+seed&aqs=chrome..69i57j69i60j0l4.2087j0j7&sourceid=chrome&ie=UTF-8)